[package]
name = "ip_lookup_service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
maxminddb = "0.17"  # For accessing MaxMind databases
serde = { version = "1.0", features = ["derive"] }  # For JSON serialization
serde_json = "1.0.133"

