[package]
name = "ip-info-site"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
actix-files = "0.6"
maxminddb = "0.23"  # For accessing MaxMind databases
serde = { version = "1.0", features = ["derive"] }  # For JSON serialization
serde_json = "1.0"
